# Generated by Django 4.2.2 on 2023-07-02 17:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField()),
                ('temperature', models.PositiveIntegerField()),
                ('humidity', models.PositiveIntegerField()),
                ('cloudiness', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('altitude', models.PositiveIntegerField()),
                ('weather_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xplorer.simpleweather')),
            ],
        ),
    ]
