# Generated by Django 4.2.2 on 2023-07-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("xplorer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleStationWeather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_time", models.DateTimeField()),
                ("temperature", models.PositiveIntegerField()),
                ("humidity", models.PositiveIntegerField()),
                ("cloudiness", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="weatherstation",
            name="weather_history",
        ),
        migrations.DeleteModel(
            name="SimpleWeather",
        ),
        migrations.AddField(
            model_name="simplestationweather",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="xplorer.weatherstation"
            ),
        ),
    ]
