# Generated by Django 4.2.2 on 2023-07-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xplorer", "0002_simplestationweather_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simplestationweather",
            name="temperature",
            field=models.FloatField(),
        ),
    ]
